name: Build and Push to GCP Artifact Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ vars.GCP_PROJECT_ID }}
        service_account_key: ${{ vars.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Configure Docker to use Artifact Registry
      run: gcloud auth configure-docker ${{ vars.GCP_ARTIFACT_REGISTRY_REGION }}.pkg.dev

    - name: Build Docker image
      run: |
        IMAGE_NAME=${{ vars.GCP_ARTIFACT_REGISTRY_REGION }}.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_ARTIFACT_REGISTRY_REPO }}/application
        GIT_COMMIT_ID=$(git rev-parse --short HEAD)
        docker build -t $IMAGE_NAME:$GIT_COMMIT_ID application

    - name: Push Docker image to Artifact Registry
      run: |
        IMAGE_NAME=${{ vars.GCP_ARTIFACT_REGISTRY_REGION }}.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_ARTIFACT_REGISTRY_REPO }}/application
        GIT_COMMIT_ID=$(git rev-parse --short HEAD)
        docker push $IMAGE_NAME:$GIT_COMMIT_ID

    - name: Verify pushed image
      run: |
        IMAGE_NAME=${{ vars.GCP_ARTIFACT_REGISTRY_REGION }}.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_ARTIFACT_REGISTRY_REPO }}/application
        GIT_COMMIT_ID=$(git rev-parse --short HEAD)
        gcloud artifacts docker images describe $IMAGE_NAME:$GIT_COMMIT_ID
